lazy push
Signed-off-by: Anirudh Gupta <anirudhgupta109@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -3,20 +3,16 @@ OUTFD=$2
 ZIP=$3
 VA="/dev/block/bootdevice/by-name/vendor_a"
 VB="/dev/block/bootdevice/by-name/vendor_b"
+testname="OnePlus6"
+
 ui_print() {
   echo -n -e "ui_print $1\n" > /proc/self/fd/$OUTFD
   echo -n -e "ui_print\n" > /proc/self/fd/$OUTFD
 }
 
+ui_print "Extracting files..."
 
-ui_print "- Mounting /system"
-
-mount /system
-mount -o rw,remount /system
-mount -o rw,remount /system /system
-
-ui_print "Extracting files"
-
+mkdir /tmp
 cd /tmp
 mkdir bin
 cd bin
@@ -24,8 +20,52 @@ unzip -o "$ZIP"
 
 TMP=$(pwd)
 MNT=$(pwd)/mntpls
+BB=$(pwd)/busybox
 
 chmod 777 $(pwd)/mntpls
+chmod 777 $(pwd)/busybox
+
+abort() {
+  ui_print "$*";
+  exit 1;
+}
+
+file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
+
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
+elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.product 2>/dev/null)" ]; then
+  getprop() {
+    ($(which getprop) | $BB grep "$1" | $BB cut -d[ -f3 | $BB cut -d] -f1) 2>/dev/null;
+  }
+fi;
+
+device="$(getprop ro.product.device)";
+product="$(getprop ro.build.product)";
+
+if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
+  ui_print "$testname";
+  match=1;
+  break;
+fi;
+ui_print " ";
+if [ ! "$match" ]; then
+  abort "Unsupported device. Aborting...";
+fi;
+
+ui_print "===================================================="
+ui_print "Vendor flasher based on OxygenOS 9.0.6 for Enchilada"
+ui_print "        By: @Surge1223 and @anirudhgupta109         "
+ui_print "===================================================="
+ui_print "- Mounting /system"
+
+mount /system
+mount -o rw,remount /system
+mount -o rw,remount /system /system
 
 ui_print "- Flashing Vendors"
 
@@ -39,4 +79,8 @@ $MNT /system ro
 
 umount /system
 
-ui_print "- Annnnd thats a wrap!"
+ui_print " "
+ui_print "Annnnd thats a wrap!"
+ui_print "NEVER wipe vendor or system on the OP6"
+ui_print " "
+ui_print "From: anirudhgupta109 (AOSiP OP6)"
